sudo: required

services:
  - docker

before_install:
  - docker build -t compex/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true compex/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  origin: "eu-north-1"
  app: "MyApp"
  env: "MyApp-env"
  bucket_name: "elasticbeanstalk-eu-north-1-644391658267"
  bucket_path: "MyApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
